# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cnstrt1.xdc

# Block Designs: bd/Image3/Image3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Image3 || ORIG_REF_NAME==Image3} -quiet] -quiet

# IP: bd/Image3/ip/Image3_blk_mem_gen_0_0/Image3_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Image3_blk_mem_gen_0_0 || ORIG_REF_NAME==Image3_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/Image1/Image1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Image1 || ORIG_REF_NAME==Image1} -quiet] -quiet

# IP: bd/Image1/ip/Image1_blk_mem_gen_0_0/Image1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Image1_blk_mem_gen_0_0 || ORIG_REF_NAME==Image1_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/Image3/Image3_ooc.xdc

# XDC: bd/Image1/Image1_ooc.xdc
